services:
  postgre:
    image: postgres:13
    ports:
      - 5432:5432
    container_name: enjoy_postgre
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enjoy