services:
  postgre:
    image: postgres:13
    ports:
      - 5432:5432
    container_name: zenn_postgre
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zenn
      POSTGRES_PASSWORD: zenn
      POSTGRES_DB: zenn